// <auto-generated />
using System;
using EdirneGeziAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EdirneGeziAPI.Migrations
{
    [DbContext(typeof(GeziDbContext))]
    [Migration("20260424091532_AddUserRole")]
    partial class AddUserRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EdirneGeziAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tarihi Eser"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Müze"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yöresel Lezzet"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Doğa ve Park"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tarihi Çarşı"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tarihi Hamam"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Etkinlik ve Festival"
                        });
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Mimar Sinan'ın ustalık eseri.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Selimiye_Mosque_in_Edirne.jpg/1024px-Selimiye_Mosque_in_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5594 41.678)"),
                            Name = "Selimiye Camii"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Meşhur Edirne tava ciğeri.",
                            ImageUrl = "https://images.deliveryhero.io/image/otlob/Products/296726/Main.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.555 41.675)"),
                            Name = "Tarihi Ciğerci Niyazi Usta"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Gün batımının harika izlendiği tarihi köprü.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Edirne_Meric_Bridge.jpg/1024px-Edirne_Meric_Bridge.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5492 41.6633)"),
                            Name = "Meriç Köprüsü"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Su ve müzik sesiyle şifa dağıtan tarihi mekan.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Complex_of_Sultan_Bayezid_II_Health_Museum.jpg/1024px-Complex_of_Sultan_Bayezid_II_Health_Museum.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5414 41.6853)"),
                            Name = "Sağlık Müzesi (II. Bayezid Külliyesi)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Meriç nehri kıyısında devasa doğa parkı.",
                            ImageUrl = "https://edirne.bel.tr/wp-content/uploads/2023/06/sogutluk.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.535 41.66)"),
                            Name = "Söğütlük Kent Ormanı"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Devasa hat yazılarıyla ünlü tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Edirne_Old_Mosque_Interior.jpg/1024px-Edirne_Old_Mosque_Interior.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5555 41.6766)"),
                            Name = "Eski Camii"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Selimiye'nin karşısındaki efsanevi ciğerci.",
                            ImageUrl = "https://www.aydinciğer.com/img/slider1.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5552 41.676)"),
                            Name = "Aydın Tava Ciğer"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Şehrin binlerce yıllık tarihini anlatan müze.",
                            ImageUrl = "https://edirnekentmuzesi.org.tr/wp-content/uploads/2021/05/muze-bina.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5582 41.6789)"),
                            Name = "Edirne Kent Müzesi"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Mimar Sinan'ın Edirne'deki muazzam kervansarayı.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Rustem_Pasha_Caravanserai_Edirne.jpg/1024px-Rustem_Pasha_Caravanserai_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5561 41.6758)"),
                            Name = "Rüstem Paşa Kervansarayı"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Tarihi güreşlerin yapıldığı yeşil alan.",
                            ImageUrl = "https://edirne.bel.tr/wp-content/uploads/2023/07/kirkpinar.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5588 41.6931)"),
                            Name = "Sarayiçi Kırkpınar Er Meydanı"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Osmanlı mimarisinde yeni bir dönemi başlatan eser.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Uc_Serefeli_Mosque.jpg/1024px-Uc_Serefeli_Mosque.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5539 41.6778)"),
                            Name = "Üç Şerefeli Camii"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Edirne savunmasının kahramanı Şükrü Paşa'nın anıtı.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/MART/26/sukru-pasa.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5645 41.6822)"),
                            Name = "Şükrü Paşa Anıtı ve Balkan Savaşı Müzesi"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Günümüzde Trakya Üniversitesi Güzel Sanatlar Fakültesi olan tarihi gar.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Karaagac_Railway_Station_Edirne.jpg/1024px-Karaagac_Railway_Station_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5292 41.65)"),
                            Name = "Karaağaç Tarihi Tren Garı"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Karaağaç'ta bulunan ve Lozan Barış Antlaşması'nı simgeleyen anıt.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Lausanne_Treaty_Monument_Edirne.jpg/1024px-Lausanne_Treaty_Monument_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5285 41.6495)"),
                            Name = "Lozan Anıtı ve Meydanı"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Edirne'nin meşhur tarihi badem ezmecisi.",
                            ImageUrl = "https://www.kececizade.com/images/kategori-resimler/badem-ezmesi.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.554 41.676)"),
                            Name = "Keçecizade Badem Ezmecisi"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Ciğer sevmeyenler için Edirne'nin en meşhur tarihi köftecisi.",
                            ImageUrl = "https://kofteciosman.com/wp-content/uploads/2019/04/kofte.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5555 41.6755)"),
                            Name = "Köfteci Osman"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Avrupa'nın en büyük sinagoglarından biri, restore edilmiş muhteşem yapı.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Great_Synagogue_of_Edirne.jpg/1024px-Great_Synagogue_of_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5511 41.6738)"),
                            Name = "Edirne Büyük Sinagogu"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Kıyık semtinde bulunan, restore edilmiş tarihi Bulgar Ortodoks kilisesi.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Sveti_Georgi_Church_Edirne.jpg/1024px-Sveti_Georgi_Church_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.568 41.686)"),
                            Name = "Sweti George Bulgar Kilisesi"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Balkanların en büyük çocuk ve interaktif eğitim müzesi.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2023/05/cocuk-muzesi.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.585 41.662)"),
                            Name = "Hasan Ali Yücel Çocuk Müzesi"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Tunca nehri üzerindeki zarif Osmanlı köprüsü.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Tunca_Bridge_Edirne.jpg/1024px-Tunca_Bridge_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5525 41.6685)"),
                            Name = "Tunca Köprüsü"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Edirne'nin ilk elektrik üretim merkezi olan, günümüzde kültür merkezi olarak kullanılan tarihi yapı.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2019/12/elektrik-fabrikasi.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5505 41.6708)"),
                            Name = "Tarihi Elektrik Fabrikası"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "Edirne Belediye Binası içinde yer alan, Atatürk'ün şehre gelişinde konakladığı ve şahsi eşyalarının sergilendiği müze oda.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2019/12/ataturk-odasi.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5564 41.6766)"),
                            Name = "Atatürk Odası"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Fatih Sultan Mehmet'in eğitim gördüğü Saatli Medrese'de kurulan, padişahın hayatını ve İstanbul'un fethini anlatan tematik müze.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/NISAN/01/fatih-muzesi/IMG_2056.JPG",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5532 41.6784)"),
                            Name = "Fatih Sultan Mehmet Müzesi"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Edirne'nin ilk özel sanat müzesi olan, içerisinde geniş resim koleksiyonları ve etnografik eserler barındıran kültür merkezi.",
                            ImageUrl = "https://osmanincimuzesi.com/wp-content/uploads/2021/04/muze-binasi.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5458 41.6742)"),
                            Name = "Osman İnci Müzesi"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Selimiye Camii külliyesi içerisindeki tarihi medresede bulunan, vakıf eserlerinin ve el yazmalarının sergilendiği müze.",
                            ImageUrl = "https://muze.gov.tr/s3/MysFileManagement/KullaniciDosyalari/BasinBulteni/44e47f20-80d4-478a-853f-7607730e704e.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5605 41.6785)"),
                            Name = "Selimiye Vakıf Müzesi"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Selimiye Camii arkasında yer alan, antik çağlardan günümüze arkeolojik ve etnografik eserlerin sergilendiği şehrin ana müzesi.",
                            ImageUrl = "https://muze.gov.tr/s3/MysFileManagement/KullaniciDosyalari/BasinBulteni/8b965825-c94a-4710-8b98-639a6742a033.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5585 41.679)"),
                            Name = "Edirne Müzesi"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Description = "Selimiye Camii avlusunda yer alan, Osmanlı dönemine ait hat, çini, ahşap ve el yazması nadide eserlerin sergilendiği müze.",
                            ImageUrl = "https://muze.gov.tr/s3/MysFileManagement/KullaniciDosyalari/BasinBulteni/44e47f20-80d4-478a-853f-7607730e704e.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5595 41.6782)"),
                            Name = "Türk İslam Eserleri Müzesi"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Balkan Savaşları'nın geçtiği tarihi Hıdırlık Tabya'da kurulan, Edirne'nin savunmasını ve Balkan tarihini canlandırmalarla sunan müze.",
                            ImageUrl = "https://muze.gov.tr/s3/MysFileManagement/KullaniciDosyalari/BasinBulteni/1d50c766-0749-410e-8566-60913c513e4b.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5415 41.685)"),
                            Name = "Balkan Tarihi Müzesi"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Description = "Edirne'nin geleneksel konak mimarisini yansıtan, içerisinde şehre özgü etnografik eserlerin ve eski yaşam kültürünün sergilendiği müze.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/TEMMUZ/09/necmi-ige-evi/WhatsApp-Image-2021_07_09-at-13_34_30.jpeg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5555 41.6738)"),
                            Name = "Necmi İge Evi Etnografya Müzesi"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "Tarihi kervansaray içerisinde yer alan, geleneksel el sanatlarından modern sergilere kadar pek çok tematik müzeye ev sahipliği yapan kültür kompleksi.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/NISAN/01/ekmekcizade/IMG_2050.JPG",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5512 41.6735)"),
                            Name = "Ekmekçizade Kervansarayı Müzeleri"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "Dünyaca ünlü heykeltıraş İlhan Koman'ın anısını yaşatan, tarihi Karaağaç Tren Garı yerleşkesinde bulunan modern sanat ve heykel müzesi.",
                            ImageUrl = "https://trakya.edu.tr/assets/images/content/haberler/icerik/612762a4-c79a-4712-9c17-48f0766d03f5.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5252 41.6515)"),
                            Name = "İlhan Koman Heykel ve Resim Müzesi"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Trakya Bölgesi'ne ait bitki ve hayvan türlerinin, fosillerin ve jeolojik materyallerin sergilendiği, üniversite bünyesindeki bilimsel müze.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2023/OCAK/06/Doga-Tarihi-Muzesi/Doga-Tarihi-Muzesi_1.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5258 41.652)"),
                            Name = "Doğa Tarihi Müzesi"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Description = "Karaağaç'ta tarihi gar binası yanında yer alan, Türkiye Cumhuriyeti'nin kuruluş belgeleri ve Milli Mücadele dönemine ait objelerin sergilendiği müze.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/NISAN/01/lozan-muzesi/IMG_2062.JPG",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5248 41.6512)"),
                            Name = "Milli Mücadele ve Lozan Müzesi"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            Description = "II. Murad tarafından Tunca Nehri kıyısında yaptırılan tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4b/Dar%C3%BCl_Hadis_Camii_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5492 41.6685)"),
                            Name = "Dar-ül Hadis Camii"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            Description = "Bizans sınırında görev yapan akıncı beyi Gazi Mihal tarafından yaptırılan tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4e/Gazi_Mihal_Mosque_in_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5412 41.6745)"),
                            Name = "Gazi Mihal Camii"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            Description = "Defterdar Mahmut Paşa tarafından Mimar Sinan'a yaptırılan tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Defterdar_Mahmut_Pasa_Camii.jpg/1024px-Defterdar_Mahmut_Pasa_Camii.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5515 41.6758)"),
                            Name = "Defterdar Camii"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Description = "Fatih Sultan Mehmet'in eşi Sittişah Hatun tarafından yaptırılan tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4b/Sittisah_Sultan_Mosque_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5498 41.6732)"),
                            Name = "Sittişah Sultan Camii"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            Description = "Edirne'nin Kaleiçi semtinde bulunan tarihi kilise.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/NISAN/01/italyan-kilisesi/IMG_2068.JPG",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.551 41.6748)"),
                            Name = "İtalyan Katolik Kilisesi"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Description = "Mimar Sinan tarafından inşa edilen tarihi kapalı çarşı.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Ali_Pasha_Bazaar_Edirne_1.jpg/1024px-Ali_Pasha_Bazaar_Edirne_1.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5542 41.6765)"),
                            Name = "Ali Paşa Çarşısı"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Description = "Selimiye Camii'ne gelir sağlamak amacıyla inşa edilen tarihi çarşı.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Arasta_Bazaar_Edirne.jpg/1024px-Arasta_Bazaar_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5598 41.678)"),
                            Name = "Arasta Çarşısı"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "Edirne'nin en eski kapalı çarşısı.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Bedesten_Bazaar_Edirne.jpg/1024px-Bedesten_Bazaar_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5572 41.6768)"),
                            Name = "Bedesten Çarşısı"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            Description = "Osmanlı eğitim sisteminin önemli merkezlerindendir.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/NISAN/01/fatih-muzesi/IMG_2056.JPG",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5528 41.6782)"),
                            Name = "Peykler ve Saatli Medrese"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            Description = "Sultan II. Murad'ın beylerbeyi Sinan Paşa tarafından yaptırılan tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Beylerbeyi_Mosque_in_Edirne.jpg/1024px-Beylerbeyi_Mosque_in_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5455 41.6785)"),
                            Name = "Beylerbeyi Camii"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            Description = "Osmanlı hamam mimarisinin klasik özelliklerini taşıyan tarihi hamam.",
                            ImageUrl = "https://www.edirnekulturturizm.gov.tr/resim/304245,beylerbeyihamami-edirnejpg.png?0",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5458 41.6782)"),
                            Name = "Beylerbeyi Hamamı"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            Description = "Osmanlı döneminde konaklama merkezi olarak kullanılan tarihi yapı.",
                            ImageUrl = "https://www.edirne.gov.tr/kurumlar/edirne.gov.tr/Haberler/2021/NISAN/01/devecihan/IMG_2044.JPG",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5535 41.6772)"),
                            Name = "Deveci Han"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            Description = "Zemin seviyesinden aşağıda olduğu için 'Çukur Hamam' olarak da bilinen tarihi hamam.",
                            ImageUrl = "https://www.edirnekulturturizm.gov.tr/resim/304246,mezit-bey-hamami-edirnejpg.png?0",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5568 41.6767)"),
                            Name = "Mezit Bey Hamamı"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 1,
                            Description = "15. yüzyıl çinileri ve hat sanatıyla ünlü tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Muradiye_Mosque_Edirne_11.jpg/1024px-Muradiye_Mosque_Edirne_11.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5648 41.6825)"),
                            Name = "Muradiye Camii"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 6,
                            Description = "Sultan II. Murad döneminde inşa edilen tarihi hamam.",
                            ImageUrl = "https://www.edirnekulturturizm.gov.tr/resim/304247,saray-hamami-edirnejpg.png?0",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5605 41.6788)"),
                            Name = "Saray Hamamı"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 6,
                            Description = "Mimar Sinan tarafından inşa edilen görkemli hamam.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Sokollu_Mehmet_Pasha_Hamam_Edirne.jpg/1024px-Sokollu_Mehmet_Pasha_Hamam_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5585 41.6775)"),
                            Name = "Sokollu Mehmet Paşa Hamamı"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 6,
                            Description = "Kaleiçi semtinde yer alan tarihi hamam yapısı.",
                            ImageUrl = "https://www.edirnekulturturizm.gov.tr/resim/304248,yenicerihamami-edirnejpg.png?0",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5485 41.6722)"),
                            Name = "Yeniçeri Hamamı"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            Description = "Baharın gelişini simgeleyen asırlık Roman geleneği.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Kakava_Festivities_Edirne.jpg/1024px-Kakava_Festivities_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.559 41.6935)"),
                            Name = "Kakava & Hıdırellez Şenlikleri"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 7,
                            Description = "Dünyanın en eski spor organizasyonlarından biri.",
                            ImageUrl = "https://edirne.bel.tr/wp-content/uploads/2023/07/kirkpinar.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5588 41.6931)"),
                            Name = "Tarihî Kırkpınar Yağlı Güreşleri Festivali"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 7,
                            Description = "Yerel tohumların korunması amacıyla düzenlenen etkinlik.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2022/03/tohum-takas.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5545 41.676)"),
                            Name = "Tohum Takas Şenliği"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 1,
                            Description = "Karaağaç mevkisinde, 15. yüzyıl Erken Osmanlı dönemine ait tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/23/Timurtaş_Paşa_Camii.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5386 41.6444)"),
                            Name = "Timurtaş Camii"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 1,
                            Description = "Sarayiçi bölgesinde bulunan tarihi türbe.",
                            ImageUrl = "https://www.edirnekulturturizm.gov.tr/resim/hidir-baba.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.558 41.6915)"),
                            Name = "Hıdır Baba Türbesi"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 1,
                            Description = "Fatih Sultan Mehmet'in kuşçubaşısı tarafından yaptırılan tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kuscu_Dogan_Camii_Edirne.jpg/1024px-Kuscu_Dogan_Camii_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5512 41.6815)"),
                            Name = "Kuşçu Doğan Camii"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 1,
                            Description = "Edirne'nin tarihi mahallelerinden birine adını veren tarihi cami.",
                            ImageUrl = "https://www.edirnekulturturizm.gov.tr/resim/hidiragacamii-edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.562 41.6815)"),
                            Name = "Hıdıraga Camii"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 1,
                            Description = "Çelebi Sultan Mehmed'in kızı tarafından yaptırılan tarihi cami.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Selcuk_Hatun_Mosque_Edirne.jpg/1024px-Selcuk_Hatun_Mosque_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5562 41.6738)"),
                            Name = "Selçuk Hatun Camii"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 1,
                            Description = "15. yüzyılda Tunca Nehri kıyısında yaptırılan tarihi yapı.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Evliya_Kasim_Pasha_Mosque_Edirne.jpg/1024px-Evliya_Kasim_Pasha_Mosque_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.545 41.6705)"),
                            Name = "Evliya Kasımpaşa Camii"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 1,
                            Description = "Kanuni Sultan Süleyman tarafından Mimar Sinan'a yaptırılan tarihi kule.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Justice_Tower_Edirne.jpg/1024px-Justice_Tower_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5592 41.6918)"),
                            Name = "Adalet Kasrı Kulesi"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 1,
                            Description = "15. yüzyılda inşasına başlanan devasa saray kompleksi.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Edirne_Palace_Remains.jpg/1024px-Edirne_Palace_Remains.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5585 41.6925)"),
                            Name = "Edirne Sarayı (Saray-ı Cedid-i Amire)"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 2,
                            Description = "15. yüzyılda 16 kemerli görkemli tarihi taş köprü.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Gazi_Mihal_Bridge_Edirne.jpg/1024px-Gazi_Mihal_Bridge_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5407 41.6763)"),
                            Name = "Gazi Mihal Köprüsü"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 2,
                            Description = "1488 yılında inşa edilen çok kemerli tarihi taş köprü.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/II._Bayezid_Bridge_Edirne.jpg/1024px-II._Bayezid_Bridge_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5475 41.6848)"),
                            Name = "II. Bayezid Köprüsü"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 4,
                            Description = "Onlarca çeşit gülün bulunduğu tematik park.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2021/11/gul-bahcesi-acilis.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5825 41.6645)"),
                            Name = "99. Yıl Edirne Gül Bahçesi"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 4,
                            Description = "Doğa yürüyüşü ve olta balıkçılığı için tercih edilen doğal gölet alanı.",
                            ImageUrl = "https://lh5.googleusercontent.com/p/AF1QipNqYv9u-1V_v9B-Y6E9X6S4",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.8525 41.5642)"),
                            Name = "Yolageldi Köyü - Bağlar Gölü"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            Description = "1912-1913 Balkan Savaşı şehitleri anısına inşa edilen anıt alan.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Balkan_Wars_Memorial_Edirne.jpg/1024px-Balkan_Wars_Memorial_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5615 41.6922)"),
                            Name = "Balkan Şehitliği"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 2,
                            Description = "7 metrelik çapıyla Guinness Rekorlar Kitabı'na giren devasa sembolik tava.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2018/05/dev-tava.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.532 41.6665)"),
                            Name = "Dünyanın En Büyük Tavası"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            Description = "Edirne'nin kurtuluşunun 100. yılı anısına inşa edilen modern anıt kompleksi.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2022/11/100-yil-aniti.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.541 41.6885)"),
                            Name = "Edirne'nin Kurtuluşunun 100. Yıl Anıtı"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 2,
                            Description = "15. yüzyılda Edirne Sarayı bünyesinde inşa edilen tarihi hamam.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Kum_Kasri_Hamami_Edirne.jpg/1024px-Kum_Kasri_Hamami_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5582 41.6932)"),
                            Name = "Kum Kasrı Hamamı"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 2,
                            Description = "Fosil örnekleri ve bölgeye özgü biyolojik türlerin sergilendiği bilimsel müze.",
                            ImageUrl = "https://dogatarihimuzesi.trakya.edu.tr/resim/dogatarihi1.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5235 41.6528)"),
                            Name = "Trakya Üniversitesi Doğa Tarihi Müzesi"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            Description = "Balkan Savaşları'nda Edirne savunmasının merkezi olan tarihi tabya.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Hidirllik_Bastion_Edirne.jpg/1024px-Hidirllik_Bastion_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5412 41.6895)"),
                            Name = "Hıdırlık Tabyaları (Balkan Tarihi Müzesi)"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 2,
                            Description = "Klasik Osmanlı çeşme mimarisinin en güzel örneklerinden biri.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Kara_Mustafa_Pasha_Fountain_Edirne.jpg/1024px-Kara_Mustafa_Pasha_Fountain_Edirne.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5578 41.6765)"),
                            Name = "Merzifonlu Kara Mustafa Paşa Çeşmesi"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            Description = "Tunca Nehri ile çevrili Edirne'nin en önemli doğal sit alanı.",
                            ImageUrl = "https://www.edirne.bel.tr/wp-content/uploads/2019/04/tavuk-ormani.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.557 41.696)"),
                            Name = "Sarayiçi Tavuk Ormanı"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 2,
                            Description = "Geç Osmanlı dönemi sivil mimari özelliklerini taşıyan tarihi yapı.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Edirne_Police_Station.jpg/1024px-Edirne_Police_Station.jpg",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5612 41.679)"),
                            Name = "Tarihi Selimiye Karakolu"
                        });
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.Place", b =>
                {
                    b.HasOne("EdirneGeziAPI.Models.Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.Category", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
