// <auto-generated />
using EdirneGeziAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EdirneGeziAPI.Migrations
{
    [DbContext(typeof(GeziDbContext))]
    [Migration("20260310155353_Seed20EdirnePlaces")]
    partial class Seed20EdirnePlaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EdirneGeziAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tarihi Eser"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yöresel Lezzet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Müze"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Doğa ve Park"
                        });
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Mimar Sinan'ın ustalık eseri.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5594 41.678)"),
                            Name = "Selimiye Camii"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Meşhur Edirne tava ciğeri.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.555 41.675)"),
                            Name = "Tarihi Ciğerci Niyazi Usta"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Gün batımının harika izlendiği tarihi köprü.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5492 41.6633)"),
                            Name = "Meriç Köprüsü"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Su ve müzik sesiyle şifa dağıtan tarihi mekan.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5414 41.6853)"),
                            Name = "Sağlık Müzesi (II. Bayezid Külliyesi)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Meriç nehri kıyısında devasa doğa parkı.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.535 41.66)"),
                            Name = "Söğütlük Kent Ormanı"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Devasa hat yazılarıyla ünlü tarihi cami.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5555 41.6766)"),
                            Name = "Eski Cami"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Selimiye'nin karşısındaki efsanevi ciğerci.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5552 41.676)"),
                            Name = "Aydın Tava Ciğer"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Şehrin binlerce yıllık tarihini anlatan müze.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5582 41.6789)"),
                            Name = "Edirne Kent Müzesi"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Mimar Sinan'ın Edirne'deki muazzam kervansarayı.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5561 41.6758)"),
                            Name = "Rüstem Paşa Kervansarayı"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Tarihi güreşlerin yapıldığı yeşil alan.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5588 41.6931)"),
                            Name = "Sarayiçi Kırkpınar Er Meydanı"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Osmanlı mimarisinde yeni bir dönemi başlatan eser.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5539 41.6778)"),
                            Name = "Üç Şerefeli Cami"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Edirne savunmasının kahramanı Şükrü Paşa'nın anıtı.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5645 41.6822)"),
                            Name = "Şükrü Paşa Anıtı ve Balkan Savaşı Müzesi"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Günümüzde Trakya Üniversitesi Güzel Sanatlar Fakültesi olan tarihi gar.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5292 41.65)"),
                            Name = "Karaağaç Tarihi Tren Garı"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Karaağaç'ta bulunan ve Lozan Barış Antlaşması'nı simgeleyen anıt.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5285 41.6495)"),
                            Name = "Lozan Anıtı ve Meydanı"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Edirne'nin meşhur tarihi badem ezmecisi.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.554 41.676)"),
                            Name = "Keçecizade Badem Ezmecisi"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Ciğer sevmeyenler için Edirne'nin en meşhur tarihi köftecisi.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5555 41.6755)"),
                            Name = "Köfteci Osman"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Avrupa'nın en büyük sinagoglarından biri, restore edilmiş muhteşem yapı.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5511 41.6738)"),
                            Name = "Edirne Büyük Sinagogu"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Kıyık semtinde bulunan, restore edilmiş tarihi Bulgar Ortodoks kilisesi.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.568 41.686)"),
                            Name = "Sweti George Bulgar Kilisesi"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Balkanların en büyük çocuk ve interaktif eğitim müzesi.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.585 41.662)"),
                            Name = "Hasan Ali Yücel Çocuk Müzesi"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Tunca nehri üzerindeki zarif Osmanlı köprüsü.",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (26.5525 41.6685)"),
                            Name = "Tunca Köprüsü"
                        });
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.Place", b =>
                {
                    b.HasOne("EdirneGeziAPI.Models.Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EdirneGeziAPI.Models.Category", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
